# Generated by Django 5.0.7 on 2024-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_rename_detaillocation_customuser_detail_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
